name: Deploy to AWS ECS with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Configure AWS credentials for Terraform
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Update with your region

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init ./infrastructure

      # Plan Terraform deployment
      - name: Terraform Plan
        run: terraform plan -out=tfplan ./infrastructure

      # Apply Terraform deployment
      - name: Terraform Apply
        run: terraform apply -auto-approve ./infrastructure/tfplan

  docker:
    runs-on: ubuntu-latest
    needs: terraform  # Ensure Terraform is done first
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push Docker image to ECR
      - name: Build and Push Docker image to ECR
        run: |
          ECR_REPO_URI=$(terraform output -raw ecr_repository_url)
          IMAGE_TAG=latest
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          docker push $ECR_REPO_URI:$IMAGE_TAG

      # Deploy to ECS (optional, you can integrate with ECS service update)
      - name: Update ECS service
        run: |
          ECS_CLUSTER_NAME=$(terraform output -raw ecs_cluster_name)
          ECS_SERVICE_NAME=$(terraform output -raw ecs_service_name)
          IMAGE_URI=$(terraform output -raw ecr_repository_url):latest
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment --image $IMAGE_URI
